image: node:latest

cache:
  paths:
    - node_modules/


before_script:
  - npm install

stages:        
  - test

unit-test-job:   
  stage: test   
  script:
    - echo "Running unit tests..."
    - make test

lint-test-job:   
  stage: test    
  script:
    - echo "Linting code..."
    - make lint

